### ISSUE TITLE
suggestion: proxies

### ISSUE THREAD

**Issue by qizq1337** [billythegoat356/Brute#1]
if you add proxy support rather than using ur own machine for the attack, u can get better results without raping ur pc. also L7 would be very sexy of u

**Comment by qizq1337** [comment]
> With proxies it will be a lot slower. The goal of Brute is to send as much dsta as possible.

yes very true but its bad to send an attack with 1 ip

**Comment by billythegoat356** [comment]
Yes.
Brute is good for attacks on familiy internet boxes.
