### ISSUE TITLE
images

### ISSUE THREAD

**Issue by Fadi002** [billythegoat356/Brute#3]
how did you made these images ? 

like this :
![image](https://user-images.githubusercontent.com/104858775/181373915-7a6a64c8-2cfb-4fd0-a5b9-61124a1b70ae.png)
and this : 
![image](https://user-images.githubusercontent.com/104858775/181374035-6d53dcc2-8b2c-447c-a863-acebddbb8265.png)

**Comment by LopeKinz** [comment]
dall-e 2 ai

**Comment by Fadi002** [comment]
> dall-e 2 ai

ty
